spring.application.name=AutomacaoIOT
spring.datasource.url=jdbc:postgresql://localhost:5432/dispositivos_iot
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
spring.jackson.time-zone=America/Sao_Paulo

# Opcional: define a criação de tabelas
spring.jpa.hibernate.ddl-auto=create

mqtt.broker=tcp://ubunto-serve.local:1883
mqtt.client-id=api_server
mqtt.username=admin
mqtt.password=123
mqtt.qos=1

file.upload-dir=C:/uploads
# file.upload-dir=/home/uploads

time.token=15
time.refreshtoken=10080

jwt.secret="TyBtZW5pbm8gZSBjdXJpb3pvIA=="